### ISSUE TITLE
Feedback zur ersten Pflichtübung

### ISSUE THREAD

**Issue by Tubiii** [tpe-lecture/repo-10#1]
<h1>Paketname</h1>
Der Paketname ist gut gewählt.

<h1>JavaDoc</h1>
Generell ist keine JavaDoc vorhanden. Es sind zwar einige Kommentare vorhanden, jedoch nicht vollständig.
[-10 Punkte]

<h1>Coding-Standard</h1>
Einige Codes sind zwar überflüssig, aber tragen zu keinem Schaden bei. Alles richtig implementiert.

<h1>JUnit Test</h1>
Tests sind sehr umfangreich.

<h1>UML</h1>
•	Konstruktoren müssen unterstrichen werden.
[-1 Punkte]

<h1>Bewertung</h1>
<b>89 Punkte
Bitte korrigieren Sie die genannten Fehler bis zur nächsten Übungsstunde, checken Sie die Verbesserung ein und schließen Sie dann dieses Issue.</b>

**Comment by tjuenemann** [comment]
# UML
Klassendiagramm wurde mit Signavio erstellt. In Signavio können Konstruktoren leider nicht unterstrichen werden bzw. ich habe keine derartige Funktion gefunden.

**Comment by KimMoessinger** [comment]
JavaDoc

Es wurde kommentiert und die JavaDoc ist nun eingefügt.
